# Generated by Django 6.0.1 on 2026-01-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('fullstack', 'Full Stack'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('ai-ml', 'AI & ML')], default='fullstack', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
